import sys
import os

src_path = sys.argv[1]
dst_path = sys.argv[2]

try:
    with open(src_path, 'rb') as f:
        content = f.read()
except FileNotFoundError:
    print(f'Error: File {src_path} not found')
    sys.exit(1)

hex_content = ', '.join([f'0x{b:02x}' for b in content])
output_code = f'''#pragma once
#include <string_view>

// Auto-generated by CMake from {os.path.basename(src_path)}
// Do not edit this file directly.

constexpr std::string_view runtime_hpp_str() {{
    constexpr static char raw[] = {{ {hex_content}, 0 }};
    return std::string_view(raw, sizeof(raw) - 1);
}}
'''

with open(dst_path, 'w') as f:
    f.write(output_code)
