import sys
import os
import re

if len(sys.argv) < 3:
    print('Usage: runtime-converter.py <output_file> <src_file1> [<src_file2> ...]')
    sys.exit(1)

dst_path = sys.argv[1]
src_files = sys.argv[2:]

def sanitize_function_name(filename):
    """Convert filename to a valid C++ function name"""
    # Get base name with path removed
    base = os.path.basename(filename)
    # For backward compatibility: runtime.hpp -> runtime_hpp_str
    # For others: std.d.zn -> std_d_zn_str
    name = re.sub(r'[^a-zA-Z0-9]', '_', base)
    # Add suffix
    return name + '_str'

functions = []

for src_path in src_files:
    try:
        with open(src_path, 'rb') as f:
            content = f.read()
    except FileNotFoundError:
        print(f'Error: File {src_path} not found')
        sys.exit(1)
    
    hex_content = ', '.join([f'0x{b:02x}' for b in content])
    func_name = sanitize_function_name(src_path)
    
    func_code = f'''
// Generated from {os.path.basename(src_path)}
constexpr std::string_view {func_name}() {{
    constexpr static char raw[] = {{ {hex_content}, 0 }};
    return std::string_view(raw, sizeof(raw) - 1);
}}'''
    
    functions.append(func_code)

output_code = f'''#pragma once
#include <string_view>

// Auto-generated by CMake
// Do not edit this file directly.
{''.join(functions)}
'''

with open(dst_path, 'w') as f:
    f.write(output_code)
